require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AcksController do

  # This should return the minimal set of attributes required to create a valid
  # Ack. As you add validations to Ack, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all acks as @acks" do
      ack = Ack.create! valid_attributes
      get :index
      assigns(:acks).should eq([ack])
    end
  end

  describe "GET show" do
    it "assigns the requested ack as @ack" do
      ack = Ack.create! valid_attributes
      get :show, :id => ack.id.to_s
      assigns(:ack).should eq(ack)
    end
  end

  describe "GET new" do
    it "assigns a new ack as @ack" do
      get :new
      assigns(:ack).should be_a_new(Ack)
    end
  end

  describe "GET edit" do
    it "assigns the requested ack as @ack" do
      ack = Ack.create! valid_attributes
      get :edit, :id => ack.id.to_s
      assigns(:ack).should eq(ack)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ack" do
        expect {
          post :create, :ack => valid_attributes
        }.to change(Ack, :count).by(1)
      end

      it "assigns a newly created ack as @ack" do
        post :create, :ack => valid_attributes
        assigns(:ack).should be_a(Ack)
        assigns(:ack).should be_persisted
      end

      it "redirects to the created ack" do
        post :create, :ack => valid_attributes
        response.should redirect_to(Ack.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ack as @ack" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ack.any_instance.stub(:save).and_return(false)
        post :create, :ack => {}
        assigns(:ack).should be_a_new(Ack)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ack.any_instance.stub(:save).and_return(false)
        post :create, :ack => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ack" do
        ack = Ack.create! valid_attributes
        # Assuming there are no other acks in the database, this
        # specifies that the Ack created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ack.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ack.id, :ack => {'these' => 'params'}
      end

      it "assigns the requested ack as @ack" do
        ack = Ack.create! valid_attributes
        put :update, :id => ack.id, :ack => valid_attributes
        assigns(:ack).should eq(ack)
      end

      it "redirects to the ack" do
        ack = Ack.create! valid_attributes
        put :update, :id => ack.id, :ack => valid_attributes
        response.should redirect_to(ack)
      end
    end

    describe "with invalid params" do
      it "assigns the ack as @ack" do
        ack = Ack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ack.any_instance.stub(:save).and_return(false)
        put :update, :id => ack.id.to_s, :ack => {}
        assigns(:ack).should eq(ack)
      end

      it "re-renders the 'edit' template" do
        ack = Ack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ack.any_instance.stub(:save).and_return(false)
        put :update, :id => ack.id.to_s, :ack => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ack" do
      ack = Ack.create! valid_attributes
      expect {
        delete :destroy, :id => ack.id.to_s
      }.to change(Ack, :count).by(-1)
    end

    it "redirects to the acks list" do
      ack = Ack.create! valid_attributes
      delete :destroy, :id => ack.id.to_s
      response.should redirect_to(acks_url)
    end
  end

end
