require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IbitsController do

  # This should return the minimal set of attributes required to create a valid
  # Ibit. As you add validations to Ibit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all ibits as @ibits" do
      ibit = Ibit.create! valid_attributes
      get :index
      assigns(:ibits).should eq([ibit])
    end
  end

  describe "GET show" do
    it "assigns the requested ibit as @ibit" do
      ibit = Ibit.create! valid_attributes
      get :show, :id => ibit.id.to_s
      assigns(:ibit).should eq(ibit)
    end
  end

  describe "GET new" do
    it "assigns a new ibit as @ibit" do
      get :new
      assigns(:ibit).should be_a_new(Ibit)
    end
  end

  describe "GET edit" do
    it "assigns the requested ibit as @ibit" do
      ibit = Ibit.create! valid_attributes
      get :edit, :id => ibit.id.to_s
      assigns(:ibit).should eq(ibit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ibit" do
        expect {
          post :create, :ibit => valid_attributes
        }.to change(Ibit, :count).by(1)
      end

      it "assigns a newly created ibit as @ibit" do
        post :create, :ibit => valid_attributes
        assigns(:ibit).should be_a(Ibit)
        assigns(:ibit).should be_persisted
      end

      it "redirects to the created ibit" do
        post :create, :ibit => valid_attributes
        response.should redirect_to(Ibit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ibit as @ibit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ibit.any_instance.stub(:save).and_return(false)
        post :create, :ibit => {}
        assigns(:ibit).should be_a_new(Ibit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ibit.any_instance.stub(:save).and_return(false)
        post :create, :ibit => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ibit" do
        ibit = Ibit.create! valid_attributes
        # Assuming there are no other ibits in the database, this
        # specifies that the Ibit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ibit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ibit.id, :ibit => {'these' => 'params'}
      end

      it "assigns the requested ibit as @ibit" do
        ibit = Ibit.create! valid_attributes
        put :update, :id => ibit.id, :ibit => valid_attributes
        assigns(:ibit).should eq(ibit)
      end

      it "redirects to the ibit" do
        ibit = Ibit.create! valid_attributes
        put :update, :id => ibit.id, :ibit => valid_attributes
        response.should redirect_to(ibit)
      end
    end

    describe "with invalid params" do
      it "assigns the ibit as @ibit" do
        ibit = Ibit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ibit.any_instance.stub(:save).and_return(false)
        put :update, :id => ibit.id.to_s, :ibit => {}
        assigns(:ibit).should eq(ibit)
      end

      it "re-renders the 'edit' template" do
        ibit = Ibit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ibit.any_instance.stub(:save).and_return(false)
        put :update, :id => ibit.id.to_s, :ibit => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ibit" do
      ibit = Ibit.create! valid_attributes
      expect {
        delete :destroy, :id => ibit.id.to_s
      }.to change(Ibit, :count).by(-1)
    end

    it "redirects to the ibits list" do
      ibit = Ibit.create! valid_attributes
      delete :destroy, :id => ibit.id.to_s
      response.should redirect_to(ibits_url)
    end
  end

end
