require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LbitsController do

  # This should return the minimal set of attributes required to create a valid
  # Lbit. As you add validations to Lbit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all lbits as @lbits" do
      lbit = Lbit.create! valid_attributes
      get :index
      assigns(:lbits).should eq([lbit])
    end
  end

  describe "GET show" do
    it "assigns the requested lbit as @lbit" do
      lbit = Lbit.create! valid_attributes
      get :show, :id => lbit.id.to_s
      assigns(:lbit).should eq(lbit)
    end
  end

  describe "GET new" do
    it "assigns a new lbit as @lbit" do
      get :new
      assigns(:lbit).should be_a_new(Lbit)
    end
  end

  describe "GET edit" do
    it "assigns the requested lbit as @lbit" do
      lbit = Lbit.create! valid_attributes
      get :edit, :id => lbit.id.to_s
      assigns(:lbit).should eq(lbit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lbit" do
        expect {
          post :create, :lbit => valid_attributes
        }.to change(Lbit, :count).by(1)
      end

      it "assigns a newly created lbit as @lbit" do
        post :create, :lbit => valid_attributes
        assigns(:lbit).should be_a(Lbit)
        assigns(:lbit).should be_persisted
      end

      it "redirects to the created lbit" do
        post :create, :lbit => valid_attributes
        response.should redirect_to(Lbit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lbit as @lbit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lbit.any_instance.stub(:save).and_return(false)
        post :create, :lbit => {}
        assigns(:lbit).should be_a_new(Lbit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lbit.any_instance.stub(:save).and_return(false)
        post :create, :lbit => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lbit" do
        lbit = Lbit.create! valid_attributes
        # Assuming there are no other lbits in the database, this
        # specifies that the Lbit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lbit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => lbit.id, :lbit => {'these' => 'params'}
      end

      it "assigns the requested lbit as @lbit" do
        lbit = Lbit.create! valid_attributes
        put :update, :id => lbit.id, :lbit => valid_attributes
        assigns(:lbit).should eq(lbit)
      end

      it "redirects to the lbit" do
        lbit = Lbit.create! valid_attributes
        put :update, :id => lbit.id, :lbit => valid_attributes
        response.should redirect_to(lbit)
      end
    end

    describe "with invalid params" do
      it "assigns the lbit as @lbit" do
        lbit = Lbit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lbit.any_instance.stub(:save).and_return(false)
        put :update, :id => lbit.id.to_s, :lbit => {}
        assigns(:lbit).should eq(lbit)
      end

      it "re-renders the 'edit' template" do
        lbit = Lbit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lbit.any_instance.stub(:save).and_return(false)
        put :update, :id => lbit.id.to_s, :lbit => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lbit" do
      lbit = Lbit.create! valid_attributes
      expect {
        delete :destroy, :id => lbit.id.to_s
      }.to change(Lbit, :count).by(-1)
    end

    it "redirects to the lbits list" do
      lbit = Lbit.create! valid_attributes
      delete :destroy, :id => lbit.id.to_s
      response.should redirect_to(lbits_url)
    end
  end

end
