require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LeaderboardsController do

  # This should return the minimal set of attributes required to create a valid
  # Leaderboard. As you add validations to Leaderboard, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all leaderboards as @leaderboards" do
      leaderboard = Leaderboard.create! valid_attributes
      get :index
      assigns(:leaderboards).should eq([leaderboard])
    end
  end

  describe "GET show" do
    it "assigns the requested leaderboard as @leaderboard" do
      leaderboard = Leaderboard.create! valid_attributes
      get :show, :id => leaderboard.id.to_s
      assigns(:leaderboard).should eq(leaderboard)
    end
  end

  describe "GET new" do
    it "assigns a new leaderboard as @leaderboard" do
      get :new
      assigns(:leaderboard).should be_a_new(Leaderboard)
    end
  end

  describe "GET edit" do
    it "assigns the requested leaderboard as @leaderboard" do
      leaderboard = Leaderboard.create! valid_attributes
      get :edit, :id => leaderboard.id.to_s
      assigns(:leaderboard).should eq(leaderboard)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Leaderboard" do
        expect {
          post :create, :leaderboard => valid_attributes
        }.to change(Leaderboard, :count).by(1)
      end

      it "assigns a newly created leaderboard as @leaderboard" do
        post :create, :leaderboard => valid_attributes
        assigns(:leaderboard).should be_a(Leaderboard)
        assigns(:leaderboard).should be_persisted
      end

      it "redirects to the created leaderboard" do
        post :create, :leaderboard => valid_attributes
        response.should redirect_to(Leaderboard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved leaderboard as @leaderboard" do
        # Trigger the behavior that occurs when invalid params are submitted
        Leaderboard.any_instance.stub(:save).and_return(false)
        post :create, :leaderboard => {}
        assigns(:leaderboard).should be_a_new(Leaderboard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Leaderboard.any_instance.stub(:save).and_return(false)
        post :create, :leaderboard => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested leaderboard" do
        leaderboard = Leaderboard.create! valid_attributes
        # Assuming there are no other leaderboards in the database, this
        # specifies that the Leaderboard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Leaderboard.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => leaderboard.id, :leaderboard => {'these' => 'params'}
      end

      it "assigns the requested leaderboard as @leaderboard" do
        leaderboard = Leaderboard.create! valid_attributes
        put :update, :id => leaderboard.id, :leaderboard => valid_attributes
        assigns(:leaderboard).should eq(leaderboard)
      end

      it "redirects to the leaderboard" do
        leaderboard = Leaderboard.create! valid_attributes
        put :update, :id => leaderboard.id, :leaderboard => valid_attributes
        response.should redirect_to(leaderboard)
      end
    end

    describe "with invalid params" do
      it "assigns the leaderboard as @leaderboard" do
        leaderboard = Leaderboard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Leaderboard.any_instance.stub(:save).and_return(false)
        put :update, :id => leaderboard.id.to_s, :leaderboard => {}
        assigns(:leaderboard).should eq(leaderboard)
      end

      it "re-renders the 'edit' template" do
        leaderboard = Leaderboard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Leaderboard.any_instance.stub(:save).and_return(false)
        put :update, :id => leaderboard.id.to_s, :leaderboard => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested leaderboard" do
      leaderboard = Leaderboard.create! valid_attributes
      expect {
        delete :destroy, :id => leaderboard.id.to_s
      }.to change(Leaderboard, :count).by(-1)
    end

    it "redirects to the leaderboards list" do
      leaderboard = Leaderboard.create! valid_attributes
      delete :destroy, :id => leaderboard.id.to_s
      response.should redirect_to(leaderboards_url)
    end
  end

end
