require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TbitsController do

  # This should return the minimal set of attributes required to create a valid
  # Tbit. As you add validations to Tbit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tbits as @tbits" do
      tbit = Tbit.create! valid_attributes
      get :index
      assigns(:tbits).should eq([tbit])
    end
  end

  describe "GET show" do
    it "assigns the requested tbit as @tbit" do
      tbit = Tbit.create! valid_attributes
      get :show, :id => tbit.id.to_s
      assigns(:tbit).should eq(tbit)
    end
  end

  describe "GET new" do
    it "assigns a new tbit as @tbit" do
      get :new
      assigns(:tbit).should be_a_new(Tbit)
    end
  end

  describe "GET edit" do
    it "assigns the requested tbit as @tbit" do
      tbit = Tbit.create! valid_attributes
      get :edit, :id => tbit.id.to_s
      assigns(:tbit).should eq(tbit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tbit" do
        expect {
          post :create, :tbit => valid_attributes
        }.to change(Tbit, :count).by(1)
      end

      it "assigns a newly created tbit as @tbit" do
        post :create, :tbit => valid_attributes
        assigns(:tbit).should be_a(Tbit)
        assigns(:tbit).should be_persisted
      end

      it "redirects to the created tbit" do
        post :create, :tbit => valid_attributes
        response.should redirect_to(Tbit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tbit as @tbit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tbit.any_instance.stub(:save).and_return(false)
        post :create, :tbit => {}
        assigns(:tbit).should be_a_new(Tbit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tbit.any_instance.stub(:save).and_return(false)
        post :create, :tbit => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tbit" do
        tbit = Tbit.create! valid_attributes
        # Assuming there are no other tbits in the database, this
        # specifies that the Tbit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tbit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tbit.id, :tbit => {'these' => 'params'}
      end

      it "assigns the requested tbit as @tbit" do
        tbit = Tbit.create! valid_attributes
        put :update, :id => tbit.id, :tbit => valid_attributes
        assigns(:tbit).should eq(tbit)
      end

      it "redirects to the tbit" do
        tbit = Tbit.create! valid_attributes
        put :update, :id => tbit.id, :tbit => valid_attributes
        response.should redirect_to(tbit)
      end
    end

    describe "with invalid params" do
      it "assigns the tbit as @tbit" do
        tbit = Tbit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tbit.any_instance.stub(:save).and_return(false)
        put :update, :id => tbit.id.to_s, :tbit => {}
        assigns(:tbit).should eq(tbit)
      end

      it "re-renders the 'edit' template" do
        tbit = Tbit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tbit.any_instance.stub(:save).and_return(false)
        put :update, :id => tbit.id.to_s, :tbit => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tbit" do
      tbit = Tbit.create! valid_attributes
      expect {
        delete :destroy, :id => tbit.id.to_s
      }.to change(Tbit, :count).by(-1)
    end

    it "redirects to the tbits list" do
      tbit = Tbit.create! valid_attributes
      delete :destroy, :id => tbit.id.to_s
      response.should redirect_to(tbits_url)
    end
  end

end
